// Autogenerated code DO NOT EDIT BY HAND
// Generated by bijection-clojure/codegen/GeneratorWorkaroundScala.scala
package com.twitter.bijection.clojure
import clojure.lang.{AFn, IFn}
import com.twitter.bijection.{AbstractBijection, Bijection, CastInjection}

trait GeneratedIFnBijections {
  implicit def function0ToIFn[A]: Bijection[Function0[A], IFn] =
    Workaround11770.function0ToIFn[A]

  implicit def function1ToIFn[A, B]: Bijection[Function1[B, A], IFn] =
    Workaround11770.function1ToIFn[A, B]

  implicit def function2ToIFn[A, B, C]: Bijection[Function2[B, C, A], IFn] =
    Workaround11770.function2ToIFn[A, B, C]

  implicit def function3ToIFn[A, B, C, D]: Bijection[Function3[B, C, D, A], IFn] =
    Workaround11770.function3ToIFn[A, B, C, D]

  implicit def function4ToIFn[A, B, C, D, E]: Bijection[Function4[B, C, D, E, A], IFn] =
    Workaround11770.function4ToIFn[A, B, C, D, E]

  implicit def function5ToIFn[A, B, C, D, E, F]: Bijection[Function5[B, C, D, E, F, A], IFn] =
    Workaround11770.function5ToIFn[A, B, C, D, E, F]

  implicit def function6ToIFn[A, B, C, D, E, F, G]: Bijection[Function6[B, C, D, E, F, G, A], IFn] =
    Workaround11770.function6ToIFn[A, B, C, D, E, F, G]

  implicit def function7ToIFn[A, B, C, D, E, F, G, H]
      : Bijection[Function7[B, C, D, E, F, G, H, A], IFn] =
    Workaround11770.function7ToIFn[A, B, C, D, E, F, G, H]

  implicit def function8ToIFn[A, B, C, D, E, F, G, H, I]
      : Bijection[Function8[B, C, D, E, F, G, H, I, A], IFn] =
    Workaround11770.function8ToIFn[A, B, C, D, E, F, G, H, I]

  implicit def function9ToIFn[A, B, C, D, E, F, G, H, I, J]
      : Bijection[Function9[B, C, D, E, F, G, H, I, J, A], IFn] =
    Workaround11770.function9ToIFn[A, B, C, D, E, F, G, H, I, J]

  implicit def function10ToIFn[A, B, C, D, E, F, G, H, I, J, K]
      : Bijection[Function10[B, C, D, E, F, G, H, I, J, K, A], IFn] =
    Workaround11770.function10ToIFn[A, B, C, D, E, F, G, H, I, J, K]

  implicit def function11ToIFn[A, B, C, D, E, F, G, H, I, J, K, L]
      : Bijection[Function11[B, C, D, E, F, G, H, I, J, K, L, A], IFn] =
    Workaround11770.function11ToIFn[A, B, C, D, E, F, G, H, I, J, K, L]

  implicit def function12ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M]
      : Bijection[Function12[B, C, D, E, F, G, H, I, J, K, L, M, A], IFn] =
    Workaround11770.function12ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M]

  implicit def function13ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
      : Bijection[Function13[B, C, D, E, F, G, H, I, J, K, L, M, N, A], IFn] =
    Workaround11770.function13ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N]

  implicit def function14ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
      : Bijection[Function14[B, C, D, E, F, G, H, I, J, K, L, M, N, O, A], IFn] =
    Workaround11770.function14ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]

  implicit def function15ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
      : Bijection[Function15[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, A], IFn] =
    Workaround11770.function15ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]

  implicit def function16ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
      : Bijection[Function16[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, A], IFn] =
    Workaround11770.function16ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]

  implicit def function17ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
      : Bijection[Function17[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, A], IFn] =
    Workaround11770.function17ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]

  implicit def function18ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
      : Bijection[Function18[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, A], IFn] =
    Workaround11770.function18ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]

  implicit def function19ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
      : Bijection[Function19[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, A], IFn] =
    Workaround11770.function19ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]

  implicit def function20ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
      : Bijection[Function20[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, A], IFn] =
    Workaround11770.function20ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]

  implicit def function21ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
      : Bijection[
        Function21[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, A],
        IFn
      ] =
    Workaround11770
      .function21ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]

  implicit def function22ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]
      : Bijection[
        Function22[B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, A],
        IFn
      ] =
    Workaround11770
      .function22ToIFn[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]

}
