// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_messages.proto

package com.twitter.bijection.protobuf;

public final class TestMessages {
  private TestMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    MALE(0, 0),
    FEMALE(1, 1),
    ;
    
    public static final int MALE_VALUE = 0;
    public static final int FEMALE_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static Gender valueOf(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.twitter.bijection.protobuf.TestMessages.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Gender[] VALUES = {
      MALE, FEMALE, 
    };
    
    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Gender(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.twitter.bijection.protobuf.Gender)
  }
  
  public interface FatigueCountOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 target_id = 1;
    boolean hasTargetId();
    long getTargetId();
    
    // required int64 suggested_id = 2;
    boolean hasSuggestedId();
    long getSuggestedId();
    
    // required int32 serve_count = 3;
    boolean hasServeCount();
    int getServeCount();
  }
  public static final class FatigueCount extends
      com.google.protobuf.GeneratedMessage
      implements FatigueCountOrBuilder {
    // Use FatigueCount.newBuilder() to construct.
    private FatigueCount(Builder builder) {
      super(builder);
    }
    private FatigueCount(boolean noInit) {}
    
    private static final FatigueCount defaultInstance;
    public static FatigueCount getDefaultInstance() {
      return defaultInstance;
    }
    
    public FatigueCount getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.twitter.bijection.protobuf.TestMessages.internal_static_com_twitter_bijection_protobuf_FatigueCount_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.twitter.bijection.protobuf.TestMessages.internal_static_com_twitter_bijection_protobuf_FatigueCount_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 target_id = 1;
    public static final int TARGET_ID_FIELD_NUMBER = 1;
    private long targetId_;
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTargetId() {
      return targetId_;
    }
    
    // required int64 suggested_id = 2;
    public static final int SUGGESTED_ID_FIELD_NUMBER = 2;
    private long suggestedId_;
    public boolean hasSuggestedId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getSuggestedId() {
      return suggestedId_;
    }
    
    // required int32 serve_count = 3;
    public static final int SERVE_COUNT_FIELD_NUMBER = 3;
    private int serveCount_;
    public boolean hasServeCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getServeCount() {
      return serveCount_;
    }
    
    private void initFields() {
      targetId_ = 0L;
      suggestedId_ = 0L;
      serveCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTargetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuggestedId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServeCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, suggestedId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, serveCount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, suggestedId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serveCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.bijection.protobuf.TestMessages.FatigueCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.twitter.bijection.protobuf.TestMessages.FatigueCount prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.twitter.bijection.protobuf.TestMessages.FatigueCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.twitter.bijection.protobuf.TestMessages.internal_static_com_twitter_bijection_protobuf_FatigueCount_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.twitter.bijection.protobuf.TestMessages.internal_static_com_twitter_bijection_protobuf_FatigueCount_fieldAccessorTable;
      }
      
      // Construct using com.twitter.bijection.protobuf.TestMessages.FatigueCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        targetId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        suggestedId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        serveCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.twitter.bijection.protobuf.TestMessages.FatigueCount.getDescriptor();
      }
      
      public com.twitter.bijection.protobuf.TestMessages.FatigueCount getDefaultInstanceForType() {
        return com.twitter.bijection.protobuf.TestMessages.FatigueCount.getDefaultInstance();
      }
      
      public com.twitter.bijection.protobuf.TestMessages.FatigueCount build() {
        com.twitter.bijection.protobuf.TestMessages.FatigueCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.twitter.bijection.protobuf.TestMessages.FatigueCount buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.twitter.bijection.protobuf.TestMessages.FatigueCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.twitter.bijection.protobuf.TestMessages.FatigueCount buildPartial() {
        com.twitter.bijection.protobuf.TestMessages.FatigueCount result = new com.twitter.bijection.protobuf.TestMessages.FatigueCount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetId_ = targetId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.suggestedId_ = suggestedId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serveCount_ = serveCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.twitter.bijection.protobuf.TestMessages.FatigueCount) {
          return mergeFrom((com.twitter.bijection.protobuf.TestMessages.FatigueCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.twitter.bijection.protobuf.TestMessages.FatigueCount other) {
        if (other == com.twitter.bijection.protobuf.TestMessages.FatigueCount.getDefaultInstance()) return this;
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        if (other.hasSuggestedId()) {
          setSuggestedId(other.getSuggestedId());
        }
        if (other.hasServeCount()) {
          setServeCount(other.getServeCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTargetId()) {
          
          return false;
        }
        if (!hasSuggestedId()) {
          
          return false;
        }
        if (!hasServeCount()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              suggestedId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              serveCount_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 target_id = 1;
      private long targetId_ ;
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTargetId() {
        return targetId_;
      }
      public Builder setTargetId(long value) {
        bitField0_ |= 0x00000001;
        targetId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetId_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 suggested_id = 2;
      private long suggestedId_ ;
      public boolean hasSuggestedId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getSuggestedId() {
        return suggestedId_;
      }
      public Builder setSuggestedId(long value) {
        bitField0_ |= 0x00000002;
        suggestedId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSuggestedId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        suggestedId_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 serve_count = 3;
      private int serveCount_ ;
      public boolean hasServeCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getServeCount() {
        return serveCount_;
      }
      public Builder setServeCount(int value) {
        bitField0_ |= 0x00000004;
        serveCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearServeCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serveCount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.twitter.bijection.protobuf.FatigueCount)
    }
    
    static {
      defaultInstance = new FatigueCount(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.twitter.bijection.protobuf.FatigueCount)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_twitter_bijection_protobuf_FatigueCount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_twitter_bijection_protobuf_FatigueCount_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023test_messages.proto\022\036com.twitter.bijec" +
      "tion.protobuf\"L\n\014FatigueCount\022\021\n\ttarget_" +
      "id\030\001 \002(\003\022\024\n\014suggested_id\030\002 \002(\003\022\023\n\013serve_" +
      "count\030\003 \002(\005*\036\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEMAL" +
      "E\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_twitter_bijection_protobuf_FatigueCount_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_twitter_bijection_protobuf_FatigueCount_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_twitter_bijection_protobuf_FatigueCount_descriptor,
              new java.lang.String[] { "TargetId", "SuggestedId", "ServeCount", },
              com.twitter.bijection.protobuf.TestMessages.FatigueCount.class,
              com.twitter.bijection.protobuf.TestMessages.FatigueCount.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
