name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: "17"
      - run: 'sbt "; +scalafmtCheckAll; scalafmtSbtCheck"'
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - run: 'sbt "++${{matrix.scala}} mimaReportBinaryIssues"'
    strategy:
      matrix:
        java:
          - "8"
          - "11"
          - "17"
        scala:
          - "2.11.12"
          - "2.12.15"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - run: 'sbt "++${{matrix.scala}} test"'
    strategy:
      matrix:
        java:
          - "8"
          - "11"
          - "17"
        scala:
          - "2.12.15"
          - "2.13.8"
  testWithCoverageReport:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 17
      - run: sbt coverage clean test coverageReport
      - run: "bash <(curl -s https://codecov.io/bash)"
